from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FormSecund(object):
    def setupUi(self, FormSecund):
        FormSecund.setObjectName(_fromUtf8("FormSecund"))
        FormSecund.resize(789, 642)
        self.label_7 = QtGui.QLabel(FormSecund)
        self.label_7.setGeometry(QtCore.QRect(20, 155, 187, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Candara"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.layoutWidget = QtGui.QWidget(FormSecund)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 364, 751, 263))
        font = QtGui.QFont()
        font.setItalic(False)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(45)
        self.gridLayout_3.setVerticalSpacing(24)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout.addWidget(self.label_20, QtCore.Qt.AlignHCenter)
        self.lineEdit_17 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.verticalLayout.addWidget(self.lineEdit_17, QtCore.Qt.AlignHCenter)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9, QtCore.Qt.AlignHCenter)
        self.lineEdit_6 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.verticalLayout.addWidget(self.lineEdit_6, QtCore.Qt.AlignHCenter)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12, QtCore.Qt.AlignHCenter)
        self.lineEdit_9 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.verticalLayout.addWidget(self.lineEdit_9, QtCore.Qt.AlignHCenter)
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout.addWidget(self.label_15, QtCore.Qt.AlignHCenter)
        self.lineEdit_12 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setItalic(False)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.verticalLayout.addWidget(self.lineEdit_12, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_2.addWidget(self.label_19, QtCore.Qt.AlignHCenter)
        self.lineEdit_16 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.verticalLayout_2.addWidget(self.lineEdit_16, QtCore.Qt.AlignHCenter)
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_2.addWidget(self.label_10, QtCore.Qt.AlignHCenter)
        self.lineEdit_7 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.verticalLayout_2.addWidget(self.lineEdit_7, QtCore.Qt.AlignHCenter)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13, QtCore.Qt.AlignHCenter)
        self.lineEdit_10 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.verticalLayout_2.addWidget(self.lineEdit_10, QtCore.Qt.AlignHCenter)
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16, QtCore.Qt.AlignHCenter)
        self.lineEdit_13 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.verticalLayout_2.addWidget(self.lineEdit_13, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_3.addWidget(self.label_18, QtCore.Qt.AlignHCenter)
        self.lineEdit_15 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.verticalLayout_3.addWidget(self.lineEdit_15, QtCore.Qt.AlignHCenter)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11, QtCore.Qt.AlignHCenter)
        self.lineEdit_8 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.verticalLayout_3.addWidget(self.lineEdit_8, QtCore.Qt.AlignHCenter)
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_3.addWidget(self.label_14, QtCore.Qt.AlignHCenter)
        self.lineEdit_11 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.verticalLayout_3.addWidget(self.lineEdit_11, QtCore.Qt.AlignHCenter)
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_3.addWidget(self.label_17, QtCore.Qt.AlignHCenter)
        self.lineEdit_14 = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.verticalLayout_3.addWidget(self.lineEdit_14, QtCore.Qt.AlignHCenter)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Candara"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.layoutWidget_2 = QtGui.QWidget(FormSecund)
        self.layoutWidget_2.setGeometry(QtCore.QRect(71, 205, 641, 22))
        font = QtGui.QFont()
        font.setItalic(False)
        self.layoutWidget_2.setFont(font)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(36)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.comboBox = QtGui.QComboBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_2.addWidget(self.comboBox, 0, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_2.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.comboBox_3 = QtGui.QComboBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.gridLayout_2.addWidget(self.comboBox_3, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(FormSecund)
        self.label_6.setGeometry(QtCore.QRect(20, 5, 271, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Candara"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line = QtGui.QFrame(FormSecund)
        self.line.setGeometry(QtCore.QRect(20, 125, 761, 16))
        font = QtGui.QFont()
        font.setItalic(False)
        self.line.setFont(font)
        self.line.setStyleSheet(_fromUtf8("color: rgb(85, 0, 255);"))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget_3 = QtGui.QWidget(FormSecund)
        self.layoutWidget_3.setGeometry(QtCore.QRect(21, 45, 751, 52))
        font = QtGui.QFont()
        font.setItalic(False)
        self.layoutWidget_3.setFont(font)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_3 = QtGui.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout.addWidget(self.lineEdit_3, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_4 = QtGui.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout.addWidget(self.lineEdit_4, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.line_2 = QtGui.QFrame(FormSecund)
        self.line_2.setGeometry(QtCore.QRect(20, 275, 764, 16))
        font = QtGui.QFont()
        font.setItalic(False)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_8 = QtGui.QLabel(FormSecund)
        self.label_8.setGeometry(QtCore.QRect(20, 300, 321, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Candara"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))

        self.retranslateUi(FormSecund)
        QtCore.QMetaObject.connectSlotsByName(FormSecund)

    def retranslateUi(self, FormSecund):
        FormSecund.setWindowTitle(_translate("FormSecund", "Form", None))
        self.label_7.setText(_translate("FormSecund", "Seleccionar Equipos", None))
        self.label_20.setText(_translate("FormSecund", "Operario 1", None))
        self.label_9.setText(_translate("FormSecund", "Medicion No 1", None))
        self.label_12.setText(_translate("FormSecund", "Medicion No 2", None))
        self.label_15.setText(_translate("FormSecund", "Medicion No 3", None))
        self.label_19.setText(_translate("FormSecund", "Operario 2", None))
        self.label_10.setText(_translate("FormSecund", "Medicion No 1", None))
        self.label_13.setText(_translate("FormSecund", "Medicion No 2", None))
        self.label_16.setText(_translate("FormSecund", "Medicion No 3", None))
        self.label_18.setText(_translate("FormSecund", "Operario 3", None))
        self.label_11.setText(_translate("FormSecund", "Medicion No 1", None))
        self.label_14.setText(_translate("FormSecund", "Medicion No 2", None))
        self.label_17.setText(_translate("FormSecund", "Medicion No 3", None))
        self.pushButton.setText(_translate("FormSecund", "Cacular", None))
        self.label_6.setText(_translate("FormSecund", "Informacion de Experimento", None))
        self.label_2.setText(_translate("FormSecund", "Norma", None))
        self.label_3.setText(_translate("FormSecund", "Experimento", None))
        self.label.setText(_translate("FormSecund", "Categoria", None))
        self.label_4.setText(_translate("FormSecund", "Cliente", None))
        self.label_8.setText(_translate("FormSecund", "Ingresar Valores de las Mediciones", None))

