'''
Created on 25/11/2014

@author: Juanito
'''

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(791, 525)
        self.lidProye = QtGui.QLabel(Dialog)
        self.lidProye.setGeometry(QtCore.QRect(10, 10, 271, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Candara"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lidProye.setFont(font)
        self.lidProye.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.lidProye.setObjectName(_fromUtf8("lidProye"))
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(10, 110, 761, 16))
        font = QtGui.QFont()
        font.setItalic(False)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.lbSelecExp = QtGui.QLabel(Dialog)
        self.lbSelecExp.setGeometry(QtCore.QRect(10, 150, 271, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Candara"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbSelecExp.setFont(font)
        self.lbSelecExp.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.lbSelecExp.setObjectName(_fromUtf8("lbSelecExp"))
        self.pteOperarios = QtGui.QPlainTextEdit(Dialog)
        self.pteOperarios.setGeometry(QtCore.QRect(250, 350, 104, 111))
        font = QtGui.QFont()
        font.setItalic(False)
        self.pteOperarios.setFont(font)
        self.pteOperarios.setObjectName(_fromUtf8("pteOperarios"))
        self.layoutWidget_3 = QtGui.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(50, 350, 151, 58))
        font = QtGui.QFont()
        font.setItalic(False)
        self.layoutWidget_3.setFont(font)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lbOperarios = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbOperarios.setFont(font)
        self.lbOperarios.setObjectName(_fromUtf8("lbOperarios"))
        self.verticalLayout.addWidget(self.lbOperarios, QtCore.Qt.AlignHCenter)
        self.cboxOperarios = QtGui.QComboBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setItalic(False)
        self.cboxOperarios.setFont(font)
        self.cboxOperarios.setObjectName(_fromUtf8("cboxOperarios"))
        self.verticalLayout.addWidget(self.cboxOperarios)
        self.layoutWidget_2 = QtGui.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(61, 71, 431, 27))
        font = QtGui.QFont()
        font.setItalic(False)
        self.layoutWidget_2.setFont(font)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.formLayout_7 = QtGui.QFormLayout(self.layoutWidget_2)
        self.formLayout_7.setMargin(0)
        self.formLayout_7.setHorizontalSpacing(24)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.lbNombre = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbNombre.setFont(font)
        self.lbNombre.setObjectName(_fromUtf8("lbNombre"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbNombre)
        self.cboxNombre = QtGui.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.cboxNombre.setFont(font)
        self.cboxNombre.setObjectName(_fromUtf8("cboxNombre"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.cboxNombre)
        self.formLayout_7.setLayout(0, QtGui.QFormLayout.LabelRole, self.formLayout_5)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.lbCliente = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbCliente.setFont(font)
        self.lbCliente.setObjectName(_fromUtf8("lbCliente"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbCliente)
        self.cboxCliente = QtGui.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.cboxCliente.setFont(font)
        self.cboxCliente.setObjectName(_fromUtf8("cboxCliente"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.cboxCliente)
        self.formLayout_7.setLayout(0, QtGui.QFormLayout.FieldRole, self.formLayout_6)
        self.buttonIniciar = QtGui.QPushButton(Dialog)
        self.buttonIniciar.setGeometry(QtCore.QRect(330, 480, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Candara"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.buttonIniciar.setFont(font)
        self.buttonIniciar.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.buttonIniciar.setObjectName(_fromUtf8("buttonIniciar"))
        self.lbSelecOper = QtGui.QLabel(Dialog)
        self.lbSelecOper.setGeometry(QtCore.QRect(10, 300, 251, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Candara"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbSelecOper.setFont(font)
        self.lbSelecOper.setStyleSheet(_fromUtf8("color: rgb(85, 0, 80);"))
        self.lbSelecOper.setObjectName(_fromUtf8("lbSelecOper"))
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 223, 631, 27))
        font = QtGui.QFont()
        font.setItalic(False)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbCategoria = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbCategoria.setFont(font)
        self.lbCategoria.setObjectName(_fromUtf8("lbCategoria"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbCategoria)
        self.cboxCategoria = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cboxCategoria.setFont(font)
        self.cboxCategoria.setObjectName(_fromUtf8("cboxCategoria"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cboxCategoria)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lbNorma = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbNorma.setFont(font)
        self.lbNorma.setObjectName(_fromUtf8("lbNorma"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbNorma)
        self.cboxNorma = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.cboxNorma.setFont(font)
        self.cboxNorma.setObjectName(_fromUtf8("cboxNorma"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cboxNorma)
        self.gridLayout.addLayout(self.formLayout_2, 0, 1, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lbExp = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbExp.setFont(font)
        self.lbExp.setObjectName(_fromUtf8("lbExp"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbExp)
        self.cboxExp = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setPointSize(10)
        font.setItalic(False)
        self.cboxExp.setFont(font)
        self.cboxExp.setObjectName(_fromUtf8("cboxExp"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.cboxExp)
        self.gridLayout.addLayout(self.formLayout_3, 0, 2, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 270, 761, 16))
        font = QtGui.QFont()
        font.setItalic(False)
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.lidProye.setText(_translate("Dialog", "Identificacion del Proyecto", None))
        self.lbSelecExp.setText(_translate("Dialog", "Seleccionar el Experimento", None))
        self.lbOperarios.setText(_translate("Dialog", "Operarios", None))
        self.lbNombre.setText(_translate("Dialog", "Nombre:   ", None))
        self.lbCliente.setText(_translate("Dialog", "Cliente:   ", None))
        self.buttonIniciar.setText(_translate("Dialog", "Iniciar", None))
        self.lbSelecOper.setText(_translate("Dialog", "Seleccionar Operarios", None))
        self.lbCategoria.setText(_translate("Dialog", "Categoria: ", None))
        self.lbNorma.setText(_translate("Dialog", "Norma: ", None))
        self.lbExp.setText(_translate("Dialog", "Experimento: ", None))


