'''
Created on 25/11/2014

@author: Juanito
'''


# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ventanaPrincipal(object):
    def setupUi(self, ventanaPrincipal):
        ventanaPrincipal.setObjectName(_fromUtf8("ventanaPrincipal"))
        ventanaPrincipal.resize(783, 403)
        self.centralwidget = QtGui.QWidget(ventanaPrincipal)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        ventanaPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ventanaPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuEditar = QtGui.QMenu(self.menubar)
        self.menuEditar.setObjectName(_fromUtf8("menuEditar"))
        self.menuEstadistica = QtGui.QMenu(self.menubar)
        self.menuEstadistica.setObjectName(_fromUtf8("menuEstadistica"))
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        self.menuDatos = QtGui.QMenu(self.menubar)
        self.menuDatos.setObjectName(_fromUtf8("menuDatos"))
        self.menuEquipo = QtGui.QMenu(self.menuDatos)
        self.menuEquipo.setObjectName(_fromUtf8("menuEquipo"))
        self.menuOperarios = QtGui.QMenu(self.menuDatos)
        self.menuOperarios.setObjectName(_fromUtf8("menuOperarios"))
        self.menuClientes = QtGui.QMenu(self.menuDatos)
        self.menuClientes.setObjectName(_fromUtf8("menuClientes"))
        self.menuPreferencias = QtGui.QMenu(self.menubar)
        self.menuPreferencias.setObjectName(_fromUtf8("menuPreferencias"))
        self.menuVentana = QtGui.QMenu(self.menubar)
        self.menuVentana.setObjectName(_fromUtf8("menuVentana"))
        ventanaPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ventanaPrincipal)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ventanaPrincipal.setStatusBar(self.statusbar)
        self.actionNuevo_Proyecto = QtGui.QAction(ventanaPrincipal)
        self.actionNuevo_Proyecto.setShortcut(_fromUtf8(""))
        self.actionNuevo_Proyecto.setObjectName(_fromUtf8("actionNuevo_Proyecto"))
        self.actionAbrir_Proyecto = QtGui.QAction(ventanaPrincipal)
        self.actionAbrir_Proyecto.setObjectName(_fromUtf8("actionAbrir_Proyecto"))
        self.actionCortar = QtGui.QAction(ventanaPrincipal)
        self.actionCortar.setObjectName(_fromUtf8("actionCortar"))
        self.actionCopiar = QtGui.QAction(ventanaPrincipal)
        self.actionCopiar.setObjectName(_fromUtf8("actionCopiar"))
        self.actionPegar = QtGui.QAction(ventanaPrincipal)
        self.actionPegar.setObjectName(_fromUtf8("actionPegar"))
        self.actionEliminar = QtGui.QAction(ventanaPrincipal)
        self.actionEliminar.setObjectName(_fromUtf8("actionEliminar"))
        self.actionDistribuci_n = QtGui.QAction(ventanaPrincipal)
        self.actionDistribuci_n.setObjectName(_fromUtf8("actionDistribuci_n"))
        self.actionGraficos = QtGui.QAction(ventanaPrincipal)
        self.actionGraficos.setObjectName(_fromUtf8("actionGraficos"))
        self.actionGuardar = QtGui.QAction(ventanaPrincipal)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionImprimir = QtGui.QAction(ventanaPrincipal)
        self.actionImprimir.setObjectName(_fromUtf8("actionImprimir"))
        self.actionSalir = QtGui.QAction(ventanaPrincipal)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionVariables = QtGui.QAction(ventanaPrincipal)
        self.actionVariables.setObjectName(_fromUtf8("actionVariables"))
        self.actionEquipos = QtGui.QAction(ventanaPrincipal)
        self.actionEquipos.setObjectName(_fromUtf8("actionEquipos"))
        self.actionIngresar_Datos = QtGui.QAction(ventanaPrincipal)
        self.actionIngresar_Datos.setObjectName(_fromUtf8("actionIngresar_Datos"))
        self.actionTblas = QtGui.QAction(ventanaPrincipal)
        self.actionTblas.setObjectName(_fromUtf8("actionTblas"))
        self.actionMedia = QtGui.QAction(ventanaPrincipal)
        self.actionMedia.setObjectName(_fromUtf8("actionMedia"))
        self.actionVarianza = QtGui.QAction(ventanaPrincipal)
        self.actionVarianza.setObjectName(_fromUtf8("actionVarianza"))
        self.actionIngresar_Equipo = QtGui.QAction(ventanaPrincipal)
        self.actionIngresar_Equipo.setObjectName(_fromUtf8("actionIngresar_Equipo"))
        self.actionEditar_Equipo = QtGui.QAction(ventanaPrincipal)
        self.actionEditar_Equipo.setObjectName(_fromUtf8("actionEditar_Equipo"))
        self.actionEliminar_Equipo = QtGui.QAction(ventanaPrincipal)
        self.actionEliminar_Equipo.setObjectName(_fromUtf8("actionEliminar_Equipo"))
        self.actionVer_Equipos = QtGui.QAction(ventanaPrincipal)
        self.actionVer_Equipos.setObjectName(_fromUtf8("actionVer_Equipos"))
        self.actionRegistrar_Operarios = QtGui.QAction(ventanaPrincipal)
        self.actionRegistrar_Operarios.setObjectName(_fromUtf8("actionRegistrar_Operarios"))
        self.actionEditar_Operarios = QtGui.QAction(ventanaPrincipal)
        self.actionEditar_Operarios.setObjectName(_fromUtf8("actionEditar_Operarios"))
        self.actionEliminar_Operrios = QtGui.QAction(ventanaPrincipal)
        self.actionEliminar_Operrios.setObjectName(_fromUtf8("actionEliminar_Operrios"))
        self.actionVer_Operarios = QtGui.QAction(ventanaPrincipal)
        self.actionVer_Operarios.setObjectName(_fromUtf8("actionVer_Operarios"))
        self.actionRegistrar_Cliente = QtGui.QAction(ventanaPrincipal)
        self.actionRegistrar_Cliente.setObjectName(_fromUtf8("actionRegistrar_Cliente"))
        self.actionEditar_Cliente = QtGui.QAction(ventanaPrincipal)
        self.actionEditar_Cliente.setObjectName(_fromUtf8("actionEditar_Cliente"))
        self.actionEliminar_Cliente = QtGui.QAction(ventanaPrincipal)
        self.actionEliminar_Cliente.setObjectName(_fromUtf8("actionEliminar_Cliente"))
        self.actionVer_Clientes = QtGui.QAction(ventanaPrincipal)
        self.actionVer_Clientes.setObjectName(_fromUtf8("actionVer_Clientes"))
        self.menuArchivo.addAction(self.actionNuevo_Proyecto)
        self.menuArchivo.addAction(self.actionAbrir_Proyecto)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionImprimir)
        self.menuArchivo.addAction(self.actionSalir)
        self.menuEditar.addAction(self.actionCortar)
        self.menuEditar.addAction(self.actionCopiar)
        self.menuEditar.addAction(self.actionPegar)
        self.menuEditar.addAction(self.actionEliminar)
        self.menuEstadistica.addAction(self.actionDistribuci_n)
        self.menuEstadistica.addAction(self.actionTblas)
        self.menuEstadistica.addAction(self.actionMedia)
        self.menuEstadistica.addAction(self.actionVarianza)
        self.menuEstadistica.addAction(self.actionGraficos)
        self.menuEquipo.addAction(self.actionIngresar_Equipo)
        self.menuEquipo.addAction(self.actionEditar_Equipo)
        self.menuEquipo.addAction(self.actionEliminar_Equipo)
        self.menuEquipo.addAction(self.actionVer_Equipos)
        self.menuOperarios.addAction(self.actionRegistrar_Operarios)
        self.menuOperarios.addAction(self.actionEditar_Operarios)
        self.menuOperarios.addAction(self.actionEliminar_Operrios)
        self.menuOperarios.addAction(self.actionVer_Operarios)
        self.menuClientes.addAction(self.actionRegistrar_Cliente)
        self.menuClientes.addAction(self.actionEditar_Cliente)
        self.menuClientes.addAction(self.actionEliminar_Cliente)
        self.menuClientes.addAction(self.actionVer_Clientes)
        self.menuDatos.addAction(self.actionVariables)
        self.menuDatos.addAction(self.actionEquipos)
        self.menuDatos.addAction(self.actionIngresar_Datos)
        self.menuDatos.addAction(self.menuEquipo.menuAction())
        self.menuDatos.addAction(self.menuOperarios.menuAction())
        self.menuDatos.addAction(self.menuClientes.menuAction())
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuDatos.menuAction())
        self.menubar.addAction(self.menuEstadistica.menuAction())
        self.menubar.addAction(self.menuPreferencias.menuAction())
        self.menubar.addAction(self.menuVentana.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(ventanaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(ventanaPrincipal)

    def retranslateUi(self, ventanaPrincipal):
        ventanaPrincipal.setWindowTitle(_translate("ventanaPrincipal", "Asocreto", None))
        self.menuArchivo.setTitle(_translate("ventanaPrincipal", "Archivo", None))
        self.menuEditar.setTitle(_translate("ventanaPrincipal", "Editar", None))
        self.menuEstadistica.setTitle(_translate("ventanaPrincipal", "Estadistica", None))
        self.menuAyuda.setTitle(_translate("ventanaPrincipal", "Ayuda", None))
        self.menuDatos.setTitle(_translate("ventanaPrincipal", "Datos", None))
        self.menuEquipo.setTitle(_translate("ventanaPrincipal", "Equipos", None))
        self.menuOperarios.setTitle(_translate("ventanaPrincipal", "Operarios", None))
        self.menuClientes.setTitle(_translate("ventanaPrincipal", "Clientes", None))
        self.menuPreferencias.setTitle(_translate("ventanaPrincipal", "Preferencias", None))
        self.menuVentana.setTitle(_translate("ventanaPrincipal", "Ventana", None))
        self.actionNuevo_Proyecto.setText(_translate("ventanaPrincipal", "Nuevo Proyecto", None))
        self.actionAbrir_Proyecto.setText(_translate("ventanaPrincipal", "Abrir Proyecto", None))
        self.actionCortar.setText(_translate("ventanaPrincipal", "Cortar", None))
        self.actionCopiar.setText(_translate("ventanaPrincipal", "Copiar", None))
        self.actionPegar.setText(_translate("ventanaPrincipal", "Pegar", None))
        self.actionEliminar.setText(_translate("ventanaPrincipal", "Eliminar", None))
        self.actionDistribuci_n.setText(_translate("ventanaPrincipal", "Distribucion", None))
        self.actionGraficos.setText(_translate("ventanaPrincipal", "Graficos", None))
        self.actionGuardar.setText(_translate("ventanaPrincipal", "Guardar", None))
        self.actionImprimir.setText(_translate("ventanaPrincipal", "Imprimir", None))
        self.actionSalir.setText(_translate("ventanaPrincipal", "Salir", None))
        self.actionVariables.setText(_translate("ventanaPrincipal", "Crear Variables", None))
        self.actionEquipos.setText(_translate("ventanaPrincipal", "Equipos", None))
        self.actionIngresar_Datos.setText(_translate("ventanaPrincipal", "Ingresar Datos", None))
        self.actionTblas.setText(_translate("ventanaPrincipal", "Tablas", None))
        self.actionMedia.setText(_translate("ventanaPrincipal", "Media", None))
        self.actionVarianza.setText(_translate("ventanaPrincipal", "Varianza", None))
        self.actionIngresar_Equipo.setText(_translate("ventanaPrincipal", "Ingresar Equipo ", None))
        self.actionEditar_Equipo.setText(_translate("ventanaPrincipal", "Editar Equipo", None))
        self.actionEliminar_Equipo.setText(_translate("ventanaPrincipal", "Eliminar Equipo", None))
        self.actionVer_Equipos.setText(_translate("ventanaPrincipal", "Ver Equipos", None))
        self.actionRegistrar_Operarios.setText(_translate("ventanaPrincipal", "Registrar Operarios", None))
        self.actionEditar_Operarios.setText(_translate("ventanaPrincipal", "Editar Operarios", None))
        self.actionEliminar_Operrios.setText(_translate("ventanaPrincipal", "Eliminar Operarios", None))
        self.actionVer_Operarios.setText(_translate("ventanaPrincipal", "Ver Operarios", None))
        self.actionRegistrar_Cliente.setText(_translate("ventanaPrincipal", "Registrar Cliente", None))
        self.actionEditar_Cliente.setText(_translate("ventanaPrincipal", "Editar Cliente", None))
        self.actionEliminar_Cliente.setText(_translate("ventanaPrincipal", "Eliminar Cliente", None))
        self.actionVer_Clientes.setText(_translate("ventanaPrincipal", "Ver Clientes", None))

